package com.example.samuel.jupitertrail;

import com.example.samuel.jupitertrail.Enum.DifficultyEnum;

import java.util.Random;

/**
 * Created by Samuel on 27/04/2016.
 */
public class Event {

    public String EventText;
    public String[] OptionText;

    public Event(DifficultyEnum diff)
    {
        //GenerateEvent

        int options = 4;
        EventText = "Generated By Event Class Text";

        OptionText = new String[options];

        Random rand = new Random();
        for (int i = 0; i< OptionText.length; i++)
        {
            int randomNum = rand.nextInt((100 - 1) + 1) + 1;

            OptionText[i] = String.valueOf(i) + ". Text Generated By Event Class: " + String.valueOf(randomNum);
        }
    }

    public String GetOptionText(int i)
    {
        return OptionText[i];
    }
}
